import Navbar from "@/components/Navbar";
import "../styles/globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Joy Baruah",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="max-w-5xl mx-auto bg-background">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
